export const L = {
  en: {
    // ── Section headings ──────────────────────────────────────────
    experience:     'Project Experience',
    education:      'Education',
    skills:         'Skills',
    certifications: 'Certifications',
    languages:      'Languages',
    competences:    'Key Competences',
    summary:        'Summary',
    portfolio:      'Portfolio & Links',
    present:        'Present',

    // ── Experience field labels ───────────────────────────────────
    role:           'Role(s)',
    projectDesc:    'Project description',
    tasks:          'Tasks and responsibilities',
    technologies:   'Technologies used',
    methodologies:  'Methodologies, technologies and competences',
    result:         'Result',

    // ── Personal meta ─────────────────────────────────────────────
    address:          'Address',
    educationSummary: 'Education',
    itSince:          'IT experience since',
    phone:            'Phone',
    email:            'Email',
    linkedin:         'LinkedIn',
    availableFrom:    'Available from',
    workPreference:   'Work preference',
    hideContact:      'Include contact info in exports · all languages',

    // ── Competence table ──────────────────────────────────────────
    competencesFor:      'Relevant competences for',
    forProject:          'for',
    includedInExports:   '✓ Included in exports',
    addToExports:        '+ Add to exports',
    levelLabel:          'Level',
    levelExpert:         'Expert',
    lastUsed:            'Last used',
    totalYears:          'Total years',
    projects:            'Projects',
    addCompetence:       '+ Add competence',
    competenceEmpty:     'Add one card per competence requirement.',
    simpleCompetence:    'Simple format',
    competenceSimplePlaceholder: 'Describe this competence — relevant experience, and what you actually did and built…',

    // ── Buttons ───────────────────────────────────────────────────
    remove:              'Remove',
    addProject:          '+ Add project',
    addEducation:        '+ Add education',
    addCertification:    '+ Add certification',
    certsCourses:        'Certifications & Courses',
    courses:             'Courses',
    addCourse:           '+ Add course',
    institution:         'Institution',
    positions:           'List of Positions',
    addPosition:         '+ Add position',
    positionTitle:       'Title / Role',
    positionDesc:        'Description',
    positionTech:        'Technologies, methods and competences used',
    enablePositions:     'Include list of positions',
    useProjectFormat:    'Full project format',
    addSkillGroup:       '+ Add skill group',
    addLanguageBtn:      '+ Add',
    managementBadge:     'Management',
    videos:              'Video Presentations',
    addVideo:            '+ Add video',
    watchVideo:          '▶ Watch video',
    videoTitlePlaceholder: 'Video title — e.g. "Why I fit this role"',
    videoDescPlaceholder:  'Why watch this? One line shown on the card.',
    videoUrlPlaceholder:   'Paste video link (Cloudflare, Vimeo, YouTube…)',
    videoNoUrl:          'No video link yet',
    addLink:             '+ Add link',
    portfolioTitlePlaceholder: 'Title / name',
    portfolioCategoryTag: '— tag —',
    portfolioCategories: { code: 'Code', design: 'Design', project: 'Project', writing: 'Writing', other: 'Other' },
    chatExamplesLabel: 'Example usages',
    chatExamples: [
      'Rewrite my summary to emphasize backend and cloud',
      'Shorten my latest experience to the strongest bullets',
      'Fill Key Competences from my experience',
      'Reorder my skills, most relevant first',
      'Make date formats consistent across all entries',
    ],
    offerFormat: 'Offer format', offerRole: 'Role', offerLocation: 'Location',
    offerAvailableFrom: 'Available from', offerHourlyRate: 'Hourly rate',
    offerSeniority: 'Seniority', offerCapacity: 'Capacity', offerWorkMode: 'Onsite/remote',
    offerLanguages: 'Languages', offerRelevance: 'Relevance', offerKeywords: 'Keywords',
    offerGeneralInfo: 'General info', offerCopy: 'Copy', offerCopied: '✓ Copied',
    offerOpenEmail: 'Open in email', offerRegenerate: 'Regenerate teaser',
    offerDrafting: 'Drafting teaser…', offerKeywordsPlaceholder: 'Comma-separated keywords',
    offerGeneralPlaceholder: 'Other processes, current employer, etc.',
  },

  no: {
    // ── Section headings ──────────────────────────────────────────
    experience:     'Prosjekterfaring',
    education:      'Utdanning',
    skills:         'Kompetanse',
    certifications: 'Sertifiseringer',
    languages:      'Språkkunnskap',
    competences:    'Spesifikk kompetansematch',
    summary:        'Oppsummering',
    portfolio:      'Portefølje og lenker',
    present:        'Nå',

    // ── Experience field labels ───────────────────────────────────
    role:           'Rolle(r)',
    projectDesc:    'Beskrivelse av prosjektet',
    tasks:          'Konsulentens oppgaver og ansvar i prosjektet',
    technologies:   'Benyttede teknologier',
    methodologies:  'Benyttede metodikker, teknologier og kompetanser',
    result:         'Resultat',

    // ── Personal meta ─────────────────────────────────────────────
    address:          'Adresse',
    educationSummary: 'Utdanning',
    itSince:          'IT-erfaring siden',
    phone:            'Telefon',
    email:            'E-post',
    linkedin:         'LinkedIn',
    availableFrom:    'Ledig fra',
    workPreference:   'Arbeidspreferanse',
    hideContact:      'Inkluder kontaktinfo i eksport · alle språk',

    // ── Competence table ──────────────────────────────────────────
    competencesFor:      'Relevante kompetanser for',
    forProject:          'for',
    includedInExports:   '✓ Inkludert i dokumentet',
    addToExports:        '+ Legg til i dokumentet',
    levelLabel:          'Nivå',
    levelExpert:         'Ekspert',
    lastUsed:            'Sist brukt',
    totalYears:          'Totalt år',
    projects:            'Prosjekter',
    addCompetence:       '+ Legg til kompetanse',
    competenceEmpty:     'Legg til ett kort per kompetansekrav.',
    simpleCompetence:    'Enkelt format',
    competenceSimplePlaceholder: 'Beskriv kompetansen — relevant erfaring, og hva du faktisk gjorde og bygde…',

    // ── Buttons ───────────────────────────────────────────────────
    remove:              'Fjern',
    addProject:          '+ Legg til prosjekt',
    addEducation:        '+ Legg til utdanning',
    addCertification:    '+ Legg til sertifisering',
    certsCourses:        'Sertifiseringer & kurs',
    courses:             'Kurs',
    addCourse:           '+ Legg til kurs',
    institution:         'Institusjon',
    positions:           'Stillingsoversikt',
    addPosition:         '+ Legg til stilling',
    positionTitle:       'Tittel / Rolle',
    positionDesc:        'Beskrivelse',
    positionTech:        'Teknologier, metoder og kompetanser brukt',
    enablePositions:     'Inkluder stillingsoversikt',
    useProjectFormat:    'Fullt prosjektformat',
    addSkillGroup:       '+ Legg til kompetansegruppe',
    addLanguageBtn:      '+ Legg til',
    managementBadge:     'Ledelse',
    videos:              'Videopresentasjoner',
    addVideo:            '+ Legg til video',
    watchVideo:          '▶ Se video',
    videoTitlePlaceholder: 'Videotittel — f.eks. «Hvorfor jeg passer til rollen»',
    videoDescPlaceholder:  'Hvorfor se denne? Én linje som vises på kortet.',
    videoUrlPlaceholder:   'Lim inn videolenke (Cloudflare, Vimeo, YouTube…)',
    videoNoUrl:          'Ingen videolenke ennå',
    addLink:             '+ Legg til lenke',
    portfolioTitlePlaceholder: 'Tittel / navn',
    portfolioCategoryTag: '— merkelapp —',
    portfolioCategories: { code: 'Kode', design: 'Design', project: 'Prosjekt', writing: 'Skriving', other: 'Annet' },
    chatExamplesLabel: 'Eksempler på bruk',
    chatExamples: [
      'Skriv om sammendraget mitt med vekt på backend og sky',
      'Forkort siste erfaring til de sterkeste punktene',
      'Fyll ut nøkkelkompetanse fra erfaringen min',
      'Sorter ferdighetene mine, mest relevante først',
      'Gjør datoformatene konsistente i alle oppføringer',
    ],
    offerFormat: 'Tilbudsformat', offerRole: 'Rolle', offerLocation: 'Bosted',
    offerAvailableFrom: 'Ledig dato', offerHourlyRate: 'Timepris',
    offerSeniority: 'Senioritet', offerCapacity: 'Kapasitet', offerWorkMode: 'Onsite/remote',
    offerLanguages: 'Språk', offerRelevance: 'Relevans', offerKeywords: 'Nøkkelord',
    offerGeneralInfo: 'Generell info', offerCopy: 'Kopier', offerCopied: '✓ Kopiert',
    offerOpenEmail: 'Åpne i e-post', offerRegenerate: 'Regenerer teaser',
    offerDrafting: 'Skriver teaser…', offerKeywordsPlaceholder: 'Nøkkelord, kommaseparert',
    offerGeneralPlaceholder: 'Andre prosesser, nåværende arbeidsgiver, osv.',
  },

  es: {
    // ── Section headings ──────────────────────────────────────────
    experience:     'Experiencia de Proyectos',
    education:      'Educación',
    skills:         'Habilidades',
    certifications: 'Certificaciones',
    languages:      'Idiomas',
    competences:    'Competencias Clave',
    summary:        'Resumen',
    portfolio:      'Portafolio y enlaces',
    present:        'Presente',

    // ── Experience field labels ───────────────────────────────────
    role:           'Rol(es)',
    projectDesc:    'Descripción del proyecto',
    tasks:          'Tareas y responsabilidades',
    technologies:   'Tecnologías utilizadas',
    methodologies:  'Metodologías, tecnologías y competencias',
    result:         'Resultado',

    // ── Personal meta ─────────────────────────────────────────────
    address:          'Dirección',
    educationSummary: 'Educación',
    itSince:          'Experiencia en TI desde',
    phone:            'Teléfono',
    email:            'Correo electrónico',
    linkedin:         'LinkedIn',
    availableFrom:    'Disponible desde',
    workPreference:   'Preferencia de trabajo',
    hideContact:      'Incluir contacto en exportaciones · todos los idiomas',

    // ── Competence table ──────────────────────────────────────────
    competencesFor:      'Competencias relevantes para',
    forProject:          'para',
    includedInExports:   '✓ Incluido en exportaciones',
    addToExports:        '+ Añadir a exportaciones',
    levelLabel:          'Nivel',
    levelExpert:         'Experto',
    lastUsed:            'Último uso',
    totalYears:          'Años totales',
    projects:            'Proyectos',
    addCompetence:       '+ Añadir competencia',
    competenceEmpty:     'Añade una tarjeta por cada requisito de competencia.',
    simpleCompetence:    'Formato simple',
    competenceSimplePlaceholder: 'Describe esta competencia — experiencia relevante, y qué hiciste y construiste realmente…',

    // ── Buttons ───────────────────────────────────────────────────
    remove:              'Eliminar',
    addProject:          '+ Añadir proyecto',
    addEducation:        '+ Añadir educación',
    addCertification:    '+ Añadir certificación',
    certsCourses:        'Certificaciones y Cursos',
    courses:             'Cursos',
    addCourse:           '+ Añadir curso',
    institution:         'Institución',
    positions:           'Lista de Cargos',
    addPosition:         '+ Añadir cargo',
    positionTitle:       'Título / Rol',
    positionDesc:        'Descripción',
    positionTech:        'Tecnologías, métodos y competencias utilizadas',
    enablePositions:     'Incluir lista de cargos',
    useProjectFormat:    'Formato de proyecto completo',
    addSkillGroup:       '+ Añadir grupo de habilidades',
    addLanguageBtn:      '+ Añadir',
    managementBadge:     'Dirección',
    videos:              'Presentaciones en vídeo',
    addVideo:            '+ Añadir vídeo',
    watchVideo:          '▶ Ver vídeo',
    videoTitlePlaceholder: 'Título del vídeo — p. ej. «Por qué encajo en este puesto»',
    videoDescPlaceholder:  '¿Por qué verlo? Una línea que se muestra en la tarjeta.',
    videoUrlPlaceholder:   'Pega el enlace del vídeo (Cloudflare, Vimeo, YouTube…)',
    videoNoUrl:          'Aún no hay enlace de vídeo',
    addLink:             '+ Añadir enlace',
    portfolioTitlePlaceholder: 'Título / nombre',
    portfolioCategoryTag: '— etiqueta —',
    portfolioCategories: { code: 'Código', design: 'Diseño', project: 'Proyecto', writing: 'Escritura', other: 'Otro' },
    chatExamplesLabel: 'Ejemplos de uso',
    chatExamples: [
      'Reescribe mi resumen enfatizando backend y la nube',
      'Acorta mi experiencia más reciente a los puntos más fuertes',
      'Rellena las competencias clave a partir de mi experiencia',
      'Reordena mis habilidades, las más relevantes primero',
      'Unifica el formato de fechas en todas las entradas',
    ],
    offerFormat: 'Formato de oferta', offerRole: 'Rol', offerLocation: 'Ubicación',
    offerAvailableFrom: 'Disponible desde', offerHourlyRate: 'Tarifa por hora',
    offerSeniority: 'Seniority', offerCapacity: 'Capacidad', offerWorkMode: 'Presencial/remoto',
    offerLanguages: 'Idiomas', offerRelevance: 'Relevancia', offerKeywords: 'Palabras clave',
    offerGeneralInfo: 'Información general', offerCopy: 'Copiar', offerCopied: '✓ Copiado',
    offerOpenEmail: 'Abrir en correo', offerRegenerate: 'Regenerar teaser',
    offerDrafting: 'Redactando teaser…', offerKeywordsPlaceholder: 'Palabras clave, separadas por comas',
    offerGeneralPlaceholder: 'Otros procesos, empleador actual, etc.',
  },

  sv: {
    experience:     'Projekterfarenhet',
    education:      'Utbildning',
    skills:         'Färdigheter',
    certifications: 'Certifieringar',
    languages:      'Språk',
    competences:    'Nyckelkompetenser',
    summary:        'Sammanfattning',
    portfolio:      'Portfölj och länkar',
    present:        'Nuvarande',
    role:           'Roll(er)',
    projectDesc:    'Projektbeskrivning',
    tasks:          'Uppgifter och ansvar',
    technologies:   'Använda teknologier',
    methodologies:  'Metoder, teknologier och kompetenser',
    result:         'Resultat',
    address:          'Adress',
    educationSummary: 'Utbildning',
    itSince:          'IT-erfarenhet sedan',
    phone:            'Telefon',
    email:            'E-post',
    linkedin:         'LinkedIn',
    availableFrom:    'Tillgänglig från',
    workPreference:   'Arbetspreferens',
    hideContact:      'Inkludera kontaktuppgifter i export · alla språk',
    competencesFor:      'Relevanta kompetenser för',
    forProject:          'för',
    includedInExports:   '✓ Inkluderad i export',
    addToExports:        '+ Lägg till i export',
    levelLabel:          'Nivå',
    levelExpert:         'Expert',
    lastUsed:            'Senast använd',
    totalYears:          'Antal år',
    projects:            'Projekt',
    addCompetence:       '+ Lägg till kompetens',
    competenceEmpty:     'Lägg till ett kort per kompetenskrav.',
    simpleCompetence:    'Enkelt format',
    competenceSimplePlaceholder: 'Beskriv denna kompetens — relevant erfarenhet och vad du faktiskt gjorde och byggde…',
    remove:              'Ta bort',
    addProject:          '+ Lägg till projekt',
    addEducation:        '+ Lägg till utbildning',
    addCertification:    '+ Lägg till certifiering',
    certsCourses:        'Certifieringar och kurser',
    courses:             'Kurser',
    addCourse:           '+ Lägg till kurs',
    institution:         'Institution',
    positions:           'Förtroendeuppdrag',
    addPosition:         '+ Lägg till uppdrag',
    positionTitle:       'Titel / roll',
    positionDesc:        'Beskrivning',
    positionTech:        'Använda teknologier, metoder och kompetenser',
    enablePositions:     'Inkludera lista över uppdrag',
    useProjectFormat:    'Fullt projektformat',
    addSkillGroup:       '+ Lägg till färdighetsgrupp',
    addLanguageBtn:      '+ Lägg till',
    managementBadge:     'Ledning',
    videos:              'Videopresentationer',
    addVideo:            '+ Lägg till video',
    watchVideo:          '▶ Se video',
    videoTitlePlaceholder: 'Videotitel — t.ex. ”Varför jag passar för rollen”',
    videoDescPlaceholder:  'Varför se den? En rad som visas på kortet.',
    videoUrlPlaceholder:   'Klistra in videolänk (Cloudflare, Vimeo, YouTube…)',
    videoNoUrl:          'Ingen videolänk ännu',
    addLink:             '+ Lägg till länk',
    portfolioTitlePlaceholder: 'Titel / namn',
    portfolioCategoryTag: '— tagg —',
    portfolioCategories: { code: 'Kod', design: 'Design', project: 'Projekt', writing: 'Skrivande', other: 'Övrigt' },
    chatExamplesLabel: 'Exempel på användning',
    chatExamples: [
      'Skriv om min sammanfattning med fokus på backend och moln',
      'Korta ner min senaste erfarenhet till de starkaste punkterna',
      'Fyll i nyckelkompetenser från min erfarenhet',
      'Sortera mina färdigheter, mest relevanta först',
      'Gör datumformaten enhetliga i alla poster',
    ],
    offerFormat: 'Offertformat', offerRole: 'Roll', offerLocation: 'Ort',
    offerAvailableFrom: 'Tillgänglig från', offerHourlyRate: 'Timpris',
    offerSeniority: 'Senioritet', offerCapacity: 'Kapacitet', offerWorkMode: 'På plats/distans',
    offerLanguages: 'Språk', offerRelevance: 'Relevans', offerKeywords: 'Nyckelord',
    offerGeneralInfo: 'Allmän info', offerCopy: 'Kopiera', offerCopied: '✓ Kopierat',
    offerOpenEmail: 'Öppna i e-post', offerRegenerate: 'Regenerera teaser',
    offerDrafting: 'Skriver teaser…', offerKeywordsPlaceholder: 'Nyckelord, kommaseparerade',
    offerGeneralPlaceholder: 'Andra processer, nuvarande arbetsgivare, osv.',
  },

  da: {
    experience:     'Projekterfaring',
    education:      'Uddannelse',
    skills:         'Færdigheder',
    certifications: 'Certificeringer',
    languages:      'Sprog',
    competences:    'Nøglekompetencer',
    summary:        'Resumé',
    portfolio:      'Portfolio og links',
    present:        'Nuværende',
    role:           'Rolle(r)',
    projectDesc:    'Projektbeskrivelse',
    tasks:          'Opgaver og ansvar',
    technologies:   'Anvendte teknologier',
    methodologies:  'Metoder, teknologier og kompetencer',
    result:         'Resultat',
    address:          'Adresse',
    educationSummary: 'Uddannelse',
    itSince:          'IT-erfaring siden',
    phone:            'Telefon',
    email:            'E-mail',
    linkedin:         'LinkedIn',
    availableFrom:    'Ledig fra',
    workPreference:   'Arbejdspræference',
    hideContact:      'Inkludér kontaktoplysninger i eksport · alle sprog',
    competencesFor:      'Relevante kompetencer for',
    forProject:          'for',
    includedInExports:   '✓ Inkluderet i eksport',
    addToExports:        '+ Føj til eksport',
    levelLabel:          'Niveau',
    levelExpert:         'Ekspert',
    lastUsed:            'Sidst brugt',
    totalYears:          'Antal år',
    projects:            'Projekter',
    addCompetence:       '+ Tilføj kompetence',
    competenceEmpty:     'Tilføj ét kort pr. kompetencekrav.',
    simpleCompetence:    'Enkelt format',
    competenceSimplePlaceholder: 'Beskriv denne kompetence — relevant erfaring, og hvad du faktisk gjorde og byggede…',
    remove:              'Fjern',
    addProject:          '+ Tilføj projekt',
    addEducation:        '+ Tilføj uddannelse',
    addCertification:    '+ Tilføj certificering',
    certsCourses:        'Certificeringer og kurser',
    courses:             'Kurser',
    addCourse:           '+ Tilføj kursus',
    institution:         'Institution',
    positions:           'Tillidshverv',
    addPosition:         '+ Tilføj hverv',
    positionTitle:       'Titel / rolle',
    positionDesc:        'Beskrivelse',
    positionTech:        'Anvendte teknologier, metoder og kompetencer',
    enablePositions:     'Inkludér liste over hverv',
    useProjectFormat:    'Fuldt projektformat',
    addSkillGroup:       '+ Tilføj færdighedsgruppe',
    addLanguageBtn:      '+ Tilføj',
    managementBadge:     'Ledelse',
    videos:              'Videopræsentationer',
    addVideo:            '+ Tilføj video',
    watchVideo:          '▶ Se video',
    videoTitlePlaceholder: 'Videotitel — f.eks. ”Derfor passer jeg til rollen”',
    videoDescPlaceholder:  'Hvorfor se den? Én linje vist på kortet.',
    videoUrlPlaceholder:   'Indsæt videolink (Cloudflare, Vimeo, YouTube…)',
    videoNoUrl:          'Intet videolink endnu',
    addLink:             '+ Tilføj link',
    portfolioTitlePlaceholder: 'Titel / navn',
    portfolioCategoryTag: '— tag —',
    portfolioCategories: { code: 'Kode', design: 'Design', project: 'Projekt', writing: 'Skrivning', other: 'Andet' },
    chatExamplesLabel: 'Eksempler på brug',
    chatExamples: [
      'Omskriv mit resumé med fokus på backend og cloud',
      'Forkort min seneste erfaring til de stærkeste punkter',
      'Udfyld nøglekompetencer ud fra min erfaring',
      'Sortér mine færdigheder, mest relevante først',
      'Gør datoformaterne ensartede i alle poster',
    ],
    offerFormat: 'Tilbudsformat', offerRole: 'Rolle', offerLocation: 'Bopæl',
    offerAvailableFrom: 'Ledig dato', offerHourlyRate: 'Timepris',
    offerSeniority: 'Senioritet', offerCapacity: 'Kapacitet', offerWorkMode: 'På stedet/remote',
    offerLanguages: 'Sprog', offerRelevance: 'Relevans', offerKeywords: 'Nøgleord',
    offerGeneralInfo: 'Generel info', offerCopy: 'Kopiér', offerCopied: '✓ Kopieret',
    offerOpenEmail: 'Åbn i e-mail', offerRegenerate: 'Regenerér teaser',
    offerDrafting: 'Skriver teaser…', offerKeywordsPlaceholder: 'Nøgleord, kommasepareret',
    offerGeneralPlaceholder: 'Andre processer, nuværende arbejdsgiver, osv.',
  },

  pl: {
    experience:     'Doświadczenie projektowe',
    education:      'Wykształcenie',
    skills:         'Umiejętności',
    certifications: 'Certyfikaty',
    languages:      'Języki',
    competences:    'Kluczowe kompetencje',
    summary:        'Podsumowanie',
    portfolio:      'Portfolio i linki',
    present:        'Obecnie',
    role:           'Rola(-e)',
    projectDesc:    'Opis projektu',
    tasks:          'Zadania i obowiązki',
    technologies:   'Użyte technologie',
    methodologies:  'Metodyki, technologie i kompetencje',
    result:         'Rezultat',
    address:          'Adres',
    educationSummary: 'Wykształcenie',
    itSince:          'Doświadczenie IT od',
    phone:            'Telefon',
    email:            'E-mail',
    linkedin:         'LinkedIn',
    availableFrom:    'Dostępny od',
    workPreference:   'Preferencje pracy',
    hideContact:      'Uwzględnij dane kontaktowe w eksporcie · wszystkie języki',
    competencesFor:      'Kompetencje istotne dla',
    forProject:          'dla',
    includedInExports:   '✓ Uwzględnione w eksporcie',
    addToExports:        '+ Dodaj do eksportu',
    levelLabel:          'Poziom',
    levelExpert:         'Ekspert',
    lastUsed:            'Ostatnio używane',
    totalYears:          'Łączna liczba lat',
    projects:            'Projekty',
    addCompetence:       '+ Dodaj kompetencję',
    competenceEmpty:     'Dodaj jedną kartę na każde wymaganie kompetencyjne.',
    simpleCompetence:    'Prosty format',
    competenceSimplePlaceholder: 'Opisz tę kompetencję — istotne doświadczenie oraz to, co faktycznie zrobiłeś i zbudowałeś…',
    remove:              'Usuń',
    addProject:          '+ Dodaj projekt',
    addEducation:        '+ Dodaj wykształcenie',
    addCertification:    '+ Dodaj certyfikat',
    certsCourses:        'Certyfikaty i kursy',
    courses:             'Kursy',
    addCourse:           '+ Dodaj kurs',
    institution:         'Instytucja',
    positions:           'Funkcje społeczne',
    addPosition:         '+ Dodaj funkcję',
    positionTitle:       'Tytuł / rola',
    positionDesc:        'Opis',
    positionTech:        'Użyte technologie, metody i kompetencje',
    enablePositions:     'Uwzględnij listę funkcji',
    useProjectFormat:    'Pełny format projektu',
    addSkillGroup:       '+ Dodaj grupę umiejętności',
    addLanguageBtn:      '+ Dodaj',
    managementBadge:     'Zarządzanie',
    videos:              'Prezentacje wideo',
    addVideo:            '+ Dodaj wideo',
    watchVideo:          '▶ Obejrzyj wideo',
    videoTitlePlaceholder: 'Tytuł wideo — np. „Dlaczego pasuję do tej roli”',
    videoDescPlaceholder:  'Dlaczego warto obejrzeć? Jedna linijka na karcie.',
    videoUrlPlaceholder:   'Wklej link do wideo (Cloudflare, Vimeo, YouTube…)',
    videoNoUrl:          'Brak linku do wideo',
    addLink:             '+ Dodaj link',
    portfolioTitlePlaceholder: 'Tytuł / nazwa',
    portfolioCategoryTag: '— etykieta —',
    portfolioCategories: { code: 'Kod', design: 'Projektowanie', project: 'Projekt', writing: 'Pisanie', other: 'Inne' },
    chatExamplesLabel: 'Przykłady użycia',
    chatExamples: [
      'Przepisz podsumowanie z naciskiem na backend i chmurę',
      'Skróć moje najnowsze doświadczenie do najmocniejszych punktów',
      'Uzupełnij kluczowe kompetencje na podstawie mojego doświadczenia',
      'Uporządkuj umiejętności, od najbardziej istotnych',
      'Ujednolić format dat we wszystkich pozycjach',
    ],
    offerFormat: 'Format oferty', offerRole: 'Rola', offerLocation: 'Lokalizacja',
    offerAvailableFrom: 'Dostępny od', offerHourlyRate: 'Stawka godzinowa',
    offerSeniority: 'Poziom', offerCapacity: 'Dostępność', offerWorkMode: 'Stacjonarnie/zdalnie',
    offerLanguages: 'Języki', offerRelevance: 'Trafność', offerKeywords: 'Słowa kluczowe',
    offerGeneralInfo: 'Informacje ogólne', offerCopy: 'Kopiuj', offerCopied: '✓ Skopiowano',
    offerOpenEmail: 'Otwórz w e-mailu', offerRegenerate: 'Wygeneruj ponownie',
    offerDrafting: 'Tworzenie tekstu…', offerKeywordsPlaceholder: 'Słowa kluczowe, oddzielone przecinkami',
    offerGeneralPlaceholder: 'Inne procesy, obecny pracodawca itd.',
  },
}

export function getL(lang) {
  return L[lang] || L.en
}

// Video placement tags (localized, content-language). Shared by the PDF/DOCX/
// share/editor video renderers so a single source stays in sync across languages.
export const VIDEO_PLACEMENTS = {
  en: { intro: 'Introduction', motivation: 'Motivation', experience: 'Experience', general: 'General' },
  no: { intro: 'Introduksjon',  motivation: 'Motivasjon',  experience: 'Erfaring',    general: 'Generell' },
  es: { intro: 'Introducción',  motivation: 'Motivación',  experience: 'Experiencia', general: 'General' },
  sv: { intro: 'Introduktion',  motivation: 'Motivation',  experience: 'Erfarenhet',  general: 'Allmän' },
  da: { intro: 'Introduktion',  motivation: 'Motivation',  experience: 'Erfaring',    general: 'Generel' },
  pl: { intro: 'Wprowadzenie',  motivation: 'Motywacja',   experience: 'Doświadczenie', general: 'Ogólne' },
}
export function videoPlacement(pl, lang) {
  return (VIDEO_PLACEMENTS[lang] || VIDEO_PLACEMENTS.en)[pl] || ''
}

// ── Feedback section labels ──────────────────────────────────────
// Display names for the structured section keys agents return
// (FEEDBACK_SECTION_KEYS in @lib/cv/schema).
export const FEEDBACK_SECTION_LABELS = {
  summary:        { en: 'Summary',        no: 'Sammendrag',      es: 'Resumen' },
  skills:         { en: 'Skills',         no: 'Ferdigheter',     es: 'Habilidades' },
  competences:    { en: 'Competences',    no: 'Kompetanse',      es: 'Competencias' },
  experience:     { en: 'Experience',     no: 'Erfaring',        es: 'Experiencia' },
  positions:      { en: 'Positions',      no: 'Verv',            es: 'Cargos' },
  education:      { en: 'Education',      no: 'Utdanning',       es: 'Educación' },
  certifications: { en: 'Certifications', no: 'Sertifiseringer', es: 'Certificaciones' },
  languages:      { en: 'Languages',      no: 'Språk',           es: 'Idiomas' },
  portfolio:      { en: 'Portfolio',      no: 'Portefølje',      es: 'Portafolio' },
  general:        { en: 'General',        no: 'Generelt',        es: 'General' },
}

export function feedbackSectionLabel(key, lang = 'en') {
  const entry = FEEDBACK_SECTION_LABELS[key] || FEEDBACK_SECTION_LABELS.general
  return entry[lang] || entry.en
}
